apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-image
  namespace: tekton-pipelines
spec:
  params:
    - name: image
      description: Reference of the image to build
      type: string
    - name: dockerfile
      description: Path to the Dockerfile
      default: ./docker/prod.Dockerfile
      type: string
    - name: context
      description: Build context
      default: .
      type: string
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=$(params.dockerfile)
        - --context=$(workspaces.source.path)/$(params.context)
        - --destination=$(params.image)
        - --cache=true
        - --cache-ttl=24h
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: harbor-credentials
