apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../helm_charts/github-agent

# Common labels
commonLabels:
  app.kubernetes.io/name: github-agent
  app.kubernetes.io/part-of: github-issue-agent

# Common annotations
commonAnnotations:
  managed-by: kustomize
