#@ GCP Load Balancer (recommended for production)
apiVersion: v1
kind: Service
metadata:
  name: fastapi-external
  namespace: my-app
  annotations:
    cloud.google.com/load-balancer-type: "External"
    networking.gke.io/load-balancer-type: "External"
    my-app.com/description: "FastAPI external service"

spec:
  selector:
    app: fastapi
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
